# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: vi

pipeline:
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
   - name: WhitespaceTokenizer
   - name: CountVectorsFeaturizer
   - name: CountVectorsFeaturizer
     analyzer: char_wb
     min_ngram: 1
     max_ngram: 4
#   - name: LanguageModelFeaturizer
#     model_name: "bert"
#     model_weights: "bert-base-multilingual-uncased"
   - name: DIETClassifier
     batch_size: [16, 64]
     epochs: 100
   - name: EntitySynonymMapper
   - name: ResponseSelector
     epochs: 100
   - name: DIETClassifier
     threshold: 0.3
     ambiguity_threshold: 0.1
     batch_size: [8,16]

policies:
  - name: TEDPolicy
    max_history: 5
    epochs: 200
    batch_size: 20
    max_training_samples: 600
